spring.application.name=arovia-backend
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=arovia
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_OAUTH_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_OAUTH_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.redis.host=localhost
spring.redis.port=6379